import { createContext, useContext, useState, useCallback } from 'react';

// ── BCP-47 voice tags ─────────────────────────────────────────────────
export const LANG_VOICE = {
  en:  'en-IN', hi:  'hi-IN', bn:  'bn-IN', te:  'te-IN',
  mr:  'mr-IN', ta:  'ta-IN', gu:  'gu-IN', kn:  'kn-IN',
  ml:  'ml-IN', pa:  'pa-IN', or:  'or-IN', as:  'as-IN',
  ur:  'ur-IN', mai: 'hi-IN', kok: 'mr-IN', doi: 'hi-IN',
  ne:  'ne-NP', sd:  'ur-IN', sat: 'hi-IN', mni: 'bn-IN',
  bodo:'hi-IN', ks:  'ur-IN',
};

export const LANGUAGES = [
  { code:'en',  label:'English'   }, { code:'hi',  label:'हिन्दी'   },
  { code:'bn',  label:'বাংলা'     }, { code:'te',  label:'తెలుగు'   },
  { code:'mr',  label:'मराठी'     }, { code:'ta',  label:'தமிழ்'    },
  { code:'gu',  label:'ગુજરાતી'  }, { code:'kn',  label:'ಕನ್ನಡ'    },
  { code:'ml',  label:'മലയാളം'   }, { code:'pa',  label:'ਪੰਜਾਬੀ'   },
  { code:'or',  label:'ଓଡ଼ିଆ'    }, { code:'as',  label:'অসমীয়া'  },
  { code:'ur',  label:'اردو'      }, { code:'mai', label:'मैथिली'   },
  { code:'kok', label:'कोंकणी'   }, { code:'doi', label:'डोगरी'    },
  { code:'ne',  label:'नेपाली'   }, { code:'sd',  label:'سنڌي'     },
  { code:'sat', label:'ᱥᱟᱱᱛᱟᱲᱤ'  }, { code:'mni', label:'মেইতেই'  },
  { code:'bodo',label:'बड़ो'      }, { code:'ks',  label:'کٲشُر'    },
];

export const isRTL = (code) => ['ur','sd','ks'].includes(code);

// ── Full translation table ────────────────────────────────────────────
const TRANSLATIONS = {
  en: {
    // nav
    registerPatient:'Register Patient', vitalsAndTriage:'Vitals & Triage',
    patientList:'Patient List', consultation:'Consultation', aiSymptomChecker:'AI Symptom Checker',
    writePrescription:'Write Prescription', prescriptionHistory:'Prescription History',
    aiTriage:'AI Triage', videoCall:'📹 Video Call', prescriptions:'Prescriptions', reminders:'Reminders',
    consultDoctor:'Consult Doctor', healthRecords:'Health Records',
    // dashboard titles
    ashaTitle:'ASHA Worker Dashboard', doctorTitle:'Doctor Dashboard', adminTitle:'Admin Panel',
    // common
    totalPatients:'Total Patients', pendingSync:'Pending Sync',
    registeredToday:'Registered Today', syncStatus:'Sync Status',
    upToDate:'Up to date', pending:'Pending',
    syncNow:'Sync Now', syncing:'Syncing...', allSynced:'All Synced',
    recordsPendingSync:'records pending sync',
    // register
    registerNewPatient:'Register New Patient', fullName:'Full Name',
    age:'Age', gender:'Gender', selectGender:'Select gender',
    male:'Male', female:'Female', other:'Other',
    phone:'Phone', address:'Address', addressOptional:'Full address (optional)',
    villageArea:'Village / Area', registerBtn:'Register Patient',
    initializing:'Initializing database...', saving:'Saving...',
    recentRegistrations:'Recent Registrations', noPatientsYet:'No patients registered yet',
    patientSavedOk:'Patient registered and saved successfully.',
    // vitals
    recordVitals:'Record Vitals', selectPatient:'Select patient',
    tempF:'Temperature (°F)', heartRate:'Heart Rate (bpm)',
    bpSystolic:'BP Systolic', bpDiastolic:'BP Diastolic',
    symptoms:'Symptoms', symptomsPlaceholder:'Describe symptoms...',
    runTriage:'Run Triage', triageResult:'AI Triage Result',
    submitVitalsFirst:'Submit vitals to see triage result',
    vitalsSavedOk:'Vitals saved and triage complete.',
    // patients table
    allPatients:'All Patients', name:'Name', ageGender:'Age / Gender',
    village:'Village', status:'Status', registered:'Registered',
    synced:'Synced', local:'Local',
    // doctor
    vitalsRecorded:'Vitals Recorded', writtenToday:'Written Today',
    writePrescriptionTitle:'Write Prescription',
    patientLabel:'Patient', diagnosis:'Diagnosis',
    prescriptionFreeText:'Prescription (free text)', additionalNotes:'Additional Notes',
    extraInstructions:'Extra instructions...',
    parseWithAI:'Parse with AI', structuredPreview:'Structured Preview',
    savePrescription:'Save Prescription', clear:'Clear',
    parseFirst:'Enter prescription text and click Parse with AI to structure it',
    prescriptionSavedOk:'Prescription saved successfully.',
    prescriptionHistory2:'Prescription History', medicines:'Medicines', date:'Date',
    noTriageYet:'No vitals recorded yet. ASHA workers submit vitals from their dashboard.',
    noPrescrYet:'No prescriptions written yet', prescriptionWritten:'Prescription written',
    // patient
    welcomeBack:'Welcome back', pending2:'Pending Today', completed:'Completed', activeMeds:'Active Meds',
    yourPrescriptions:'Your Prescriptions', noPrescrPatient:'No prescriptions yet',
    noPrescrSub:'Your doctor will add them here', listenAll:'Listen All',
    medicineReminders:'Medicine Reminders', noReminders:'No reminders',
    noReminderSub:'Reminders are generated from your prescriptions',
    enableNotif:'Enable Notifications', notifActive:'Notifications active',
    markTaken:'Mark Taken', taken:'Taken',
    prescribedBy:'Prescribed by',
    // speak
    speakIntro:'Your prescription includes the following medicines.',
    speakMed:'Medicine', speakTake:'Take', speakTiming:'Timing', speakFor:'For', speakNext:'Next',
    // login page
    loginTitle:'GramHealth', loginSub:'Lite',
    loginTagline:'Rural health platform connecting patients, ASHA workers & doctors — online or offline.',
    loginSignin:'Sign in', loginSelectRole:'Select your role to get started',
    loginPatient:'Patient', loginPatientSub:'View prescriptions & consult',
    loginAsha:'ASHA Worker', loginAshaSub:'Register patients, record vitals',
    loginDoctor:'Doctor', loginDoctorSub:'Write & manage prescriptions',
    loginAdmin:'Admin', loginAdminSub:'System overview & management',
    loginUsername:'Username', loginPassword:'Password',
    loginUserPh:'Enter username', loginPassPh:'Enter password',
    loginSubmit:'Continue', loginLoading:'Signing in…',
    loginDemo:'Demo mode — any username & password',
    loginErrorFill:'Please complete all fields', loginErrorInvalid:'Invalid credentials',
    // logout
    logout:'Out',
    // misc
    dbError:'Database error. Try refreshing the page.',
    consultationTitle:'Adaptive Consultation',
    noConnectionMsg:'Consultation module available when connected to patient session.',
    low:'Low Priority', medium:'Medium Priority', high:'High Priority',
    patientName:'Patient name', ageFull:'Age', genderFull:'Gender',
    recorded:'Recorded',
  },
  hi: {
    registerPatient:'मरीज़ पंजीकरण', vitalsAndTriage:'स्वास्थ्य जांच',
    patientList:'मरीज़ सूची', consultation:'परामर्श', aiSymptomChecker:'AI लक्षण जांच',
    writePrescription:'नुस्खा लिखें', prescriptionHistory:'नुस्खा इतिहास',
    aiTriage:'AI ट्राइएज', videoCall:'📹 वीडियो कॉल', prescriptions:'नुस्खे', reminders:'याद दिलाएं',
    consultDoctor:'डॉक्टर से परामर्श', healthRecords:'स्वास्थ्य रिकॉर्ड',
    ashaTitle:'आशा कार्यकर्ता डैशबोर्ड', doctorTitle:'डॉक्टर डैशबोर्ड', adminTitle:'व्यवस्थापक पैनल',
    totalPatients:'कुल मरीज़', pendingSync:'लंबित सिंक',
    registeredToday:'आज पंजीकृत', syncStatus:'सिंक स्थिति',
    upToDate:'अपडेट है', pending:'लंबित',
    syncNow:'अभी सिंक करें', syncing:'सिंक हो रहा है...', allSynced:'सब सिंक हो गया',
    recordsPendingSync:'रिकॉर्ड सिंक होने बाकी हैं',
    registerNewPatient:'नया मरीज़ पंजीकृत करें', fullName:'पूरा नाम',
    age:'आयु', gender:'लिंग', selectGender:'लिंग चुनें',
    male:'पुरुष', female:'महिला', other:'अन्य',
    phone:'फ़ोन', address:'पता', addressOptional:'पूरा पता (वैकल्पिक)',
    villageArea:'गाँव / क्षेत्र', registerBtn:'मरीज़ पंजीकृत करें',
    initializing:'डेटाबेस शुरू हो रहा है...', saving:'सहेजा जा रहा है...',
    recentRegistrations:'हाल के पंजीकरण', noPatientsYet:'अभी कोई मरीज़ नहीं',
    patientSavedOk:'मरीज़ सफलतापूर्वक पंजीकृत हुआ।',
    recordVitals:'स्वास्थ्य जांच दर्ज करें', selectPatient:'मरीज़ चुनें',
    tempF:'तापमान (°F)', heartRate:'हृदय गति (bpm)',
    bpSystolic:'BP सिस्टोलिक', bpDiastolic:'BP डायस्टोलिक',
    symptoms:'लक्षण', symptomsPlaceholder:'लक्षणों का विवरण दें...',
    runTriage:'ट्राइएज करें', triageResult:'AI ट्राइएज परिणाम',
    submitVitalsFirst:'परिणाम देखने के लिए स्वास्थ्य जांच जमा करें',
    vitalsSavedOk:'जांच सहेजी गई और ट्राइएज पूर्ण।',
    allPatients:'सभी मरीज़', name:'नाम', ageGender:'आयु / लिंग',
    village:'गाँव', status:'स्थिति', registered:'पंजीकृत',
    synced:'सिंक हो गया', local:'स्थानीय',
    vitalsRecorded:'जांच दर्ज', writtenToday:'आज लिखे',
    writePrescriptionTitle:'नुस्खा लिखें',
    patientLabel:'मरीज़', diagnosis:'रोग निदान',
    prescriptionFreeText:'नुस्खा (मुक्त पाठ)', additionalNotes:'अतिरिक्त नोट्स',
    extraInstructions:'अतिरिक्त निर्देश...',
    parseWithAI:'AI से विश्लेषण करें', structuredPreview:'संरचित पूर्वावलोकन',
    savePrescription:'नुस्खा सहेजें', clear:'साफ़ करें',
    parseFirst:'नुस्खा टाइप करें और AI से विश्लेषण करें बटन दबाएं',
    prescriptionSavedOk:'नुस्खा सफलतापूर्वक सहेजा गया।',
    prescriptionHistory2:'नुस्खा इतिहास', medicines:'दवाइयाँ', date:'तारीख',
    noTriageYet:'अभी कोई जांच नहीं। आशा कार्यकर्ता अपने डैशबोर्ड से जांच जमा करते हैं।',
    noPrescrYet:'अभी कोई नुस्खा नहीं लिखा गया', prescriptionWritten:'नुस्खा लिखा गया',
    welcomeBack:'स्वागत है', pending2:'आज बाकी', completed:'पूर्ण', activeMeds:'सक्रिय दवाएं',
    yourPrescriptions:'आपके नुस्खे', noPrescrPatient:'अभी कोई नुस्खा नहीं',
    noPrescrSub:'आपके डॉक्टर यहाँ जोड़ेंगे', listenAll:'सभी सुनें',
    medicineReminders:'दवा याद दिलाएं', noReminders:'कोई रिमाइंडर नहीं',
    noReminderSub:'नुस्खों से रिमाइंडर बनते हैं',
    enableNotif:'सूचनाएं चालू करें', notifActive:'सूचनाएं सक्रिय',
    markTaken:'ली गई', taken:'ले ली',
    prescribedBy:'डॉक्टर',
    speakIntro:'आपके नुस्खे में निम्नलिखित दवाएं शामिल हैं।',
    speakMed:'दवा', speakTake:'लें', speakTiming:'समय', speakFor:'के लिए', speakNext:'अगला',
    loginTitle:'ग्रामहेल्थ', loginSub:'लाइट',
    loginTagline:'ग्रामीण स्वास्थ्य मंच — मरीज़, आशा कार्यकर्ता और डॉक्टर को जोड़ता है।',
    loginSignin:'साइन इन', loginSelectRole:'अपनी भूमिका चुनें',
    loginPatient:'मरीज़', loginPatientSub:'नुस्खे देखें और परामर्श करें',
    loginAsha:'आशा कार्यकर्ता', loginAshaSub:'मरीज़ पंजीकरण, स्वास्थ्य जांच',
    loginDoctor:'डॉक्टर', loginDoctorSub:'नुस्खे लिखें और प्रबंधित करें',
    loginAdmin:'व्यवस्थापक', loginAdminSub:'सिस्टम अवलोकन',
    loginUsername:'उपयोगकर्ता नाम', loginPassword:'पासवर्ड',
    loginUserPh:'उपयोगकर्ता नाम दर्ज करें', loginPassPh:'पासवर्ड दर्ज करें',
    loginSubmit:'जारी रखें', loginLoading:'साइन इन हो रहा है…',
    loginDemo:'डेमो मोड — कोई भी नाम और पासवर्ड',
    loginErrorFill:'कृपया सभी फ़ील्ड भरें', loginErrorInvalid:'अमान्य जानकारी',
    logout:'बाहर',
    dbError:'डेटाबेस में त्रुटि। पृष्ठ रीफ्रेश करें।',
    consultationTitle:'परामर्श', noConnectionMsg:'मरीज़ से जुड़ने पर परामर्श उपलब्ध होगा।',
    low:'कम गंभीर', medium:'मध्यम गंभीर', high:'अत्यधिक गंभीर',
    patientName:'मरीज़ का नाम', ageFull:'आयु', genderFull:'लिंग', recorded:'दर्ज',
  },
  bn: {
    registerPatient:'রোগী নিবন্ধন', vitalsAndTriage:'ভাইটাল ও ট্রায়াজ',
    patientList:'রোগীর তালিকা', consultation:'পরামর্শ', aiSymptomChecker:'AI লক্ষণ পরীক্ষা',
    writePrescription:'প্রেসক্রিপশন লিখুন', prescriptionHistory:'প্রেসক্রিপশন ইতিহাস',
    aiTriage:'AI ট্রায়াজ', prescriptions:'প্রেসক্রিপশন', reminders:'স্মরণ করিয়ে দিন',
    consultDoctor:'ডাক্তারের পরামর্শ', healthRecords:'স্বাস্থ্য রেকর্ড',
    ashaTitle:'আশা কর্মী ড্যাশবোর্ড', doctorTitle:'ডাক্তার ড্যাশবোর্ড', adminTitle:'প্রশাসক প্যানেল',
    totalPatients:'মোট রোগী', pendingSync:'অপেক্ষারত সিঙ্ক',
    registeredToday:'আজ নিবন্ধিত', syncStatus:'সিঙ্ক অবস্থা',
    upToDate:'আপডেট আছে', pending:'অপেক্ষারত',
    syncNow:'এখনই সিঙ্ক করুন', syncing:'সিঙ্ক হচ্ছে...', allSynced:'সব সিঙ্ক হয়েছে',
    recordsPendingSync:'রেকর্ড সিঙ্ক বাকি',
    registerNewPatient:'নতুন রোগী নিবন্ধন', fullName:'পুরো নাম',
    age:'বয়স', gender:'লিঙ্গ', selectGender:'লিঙ্গ নির্বাচন',
    male:'পুরুষ', female:'মহিলা', other:'অন্যান্য',
    phone:'ফোন', address:'ঠিকানা', addressOptional:'পূর্ণ ঠিকানা (ঐচ্ছিক)',
    villageArea:'গ্রাম / এলাকা', registerBtn:'রোগী নিবন্ধন করুন',
    initializing:'ডেটাবেস শুরু হচ্ছে...', saving:'সংরক্ষণ হচ্ছে...',
    recentRegistrations:'সাম্প্রতিক নিবন্ধন', noPatientsYet:'এখনো কোনো রোগী নেই',
    patientSavedOk:'রোগী সফলভাবে নিবন্ধিত হয়েছে।',
    recordVitals:'ভাইটাল রেকর্ড করুন', selectPatient:'রোগী নির্বাচন',
    tempF:'তাপমাত্রা (°F)', heartRate:'হৃদস্পন্দন (bpm)',
    bpSystolic:'BP সিস্টোলিক', bpDiastolic:'BP ডায়াস্টোলিক',
    symptoms:'লক্ষণ', symptomsPlaceholder:'লক্ষণ বর্ণনা করুন...',
    runTriage:'ট্রায়াজ চালান', triageResult:'AI ট্রায়াজ ফলাফল',
    submitVitalsFirst:'ফলাফল দেখতে ভাইটাল জমা দিন',
    vitalsSavedOk:'ভাইটাল সংরক্ষিত ও ট্রায়াজ সম্পন্ন।',
    allPatients:'সব রোগী', name:'নাম', ageGender:'বয়স / লিঙ্গ',
    village:'গ্রাম', status:'অবস্থা', registered:'নিবন্ধিত',
    synced:'সিঙ্ক হয়েছে', local:'স্থানীয়',
    vitalsRecorded:'ভাইটাল রেকর্ড', writtenToday:'আজ লেখা',
    writePrescriptionTitle:'প্রেসক্রিপশন লিখুন',
    patientLabel:'রোগী', diagnosis:'রোগ নির্ণয়',
    prescriptionFreeText:'প্রেসক্রিপশন (মুক্ত পাঠ)', additionalNotes:'অতিরিক্ত নোট',
    extraInstructions:'অতিরিক্ত নির্দেশনা...',
    parseWithAI:'AI দিয়ে বিশ্লেষণ', structuredPreview:'কাঠামোগত প্রিভিউ',
    savePrescription:'প্রেসক্রিপশন সংরক্ষণ', clear:'পরিষ্কার',
    parseFirst:'প্রেসক্রিপশন টাইপ করুন এবং AI দিয়ে বিশ্লেষণ করুন',
    prescriptionSavedOk:'প্রেসক্রিপশন সফলভাবে সংরক্ষিত।',
    prescriptionHistory2:'প্রেসক্রিপশন ইতিহাস', medicines:'ওষুধ', date:'তারিখ',
    noTriageYet:'এখনো কোনো ভাইটাল নেই।', noPrescrYet:'এখনো কোনো প্রেসক্রিপশন নেই',
    prescriptionWritten:'প্রেসক্রিপশন লেখা হয়েছে',
    welcomeBack:'স্বাগতম', pending2:'আজ বাকি', completed:'সম্পন্ন', activeMeds:'সক্রিয় ওষুধ',
    yourPrescriptions:'আপনার প্রেসক্রিপশন', noPrescrPatient:'এখনো কোনো প্রেসক্রিপশন নেই',
    noPrescrSub:'আপনার ডাক্তার এখানে যোগ করবেন', listenAll:'সব শুনুন',
    medicineReminders:'ওষুধ স্মরণ', noReminders:'কোনো রিমাইন্ডার নেই',
    noReminderSub:'প্রেসক্রিপশন থেকে রিমাইন্ডার তৈরি হয়',
    enableNotif:'বিজ্ঞপ্তি চালু করুন', notifActive:'বিজ্ঞপ্তি সক্রিয়',
    markTaken:'নেওয়া হয়েছে', taken:'নেওয়া হয়েছে',
    prescribedBy:'প্রেসক্রাইব করেছেন',
    speakIntro:'আপনার প্রেসক্রিপশনে নিম্নলিখিত ওষুধ আছে।',
    speakMed:'ওষুধ', speakTake:'নিন', speakTiming:'সময়', speakFor:'জন্য', speakNext:'পরবর্তী',
    loginTitle:'গ্রামহেলথ', loginSub:'লাইট',
    loginTagline:'গ্রামীণ স্বাস্থ্য প্ল্যাটফর্ম — রোগী, আশা কর্মী ও ডাক্তারকে সংযুক্ত করে।',
    loginSignin:'সাইন ইন', loginSelectRole:'আপনার ভূমিকা বেছে নিন',
    loginPatient:'রোগী', loginPatientSub:'প্রেসক্রিপশন দেখুন',
    loginAsha:'আশা কর্মী', loginAshaSub:'রোগী নিবন্ধন করুন',
    loginDoctor:'ডাক্তার', loginDoctorSub:'প্রেসক্রিপশন লিখুন',
    loginAdmin:'প্রশাসক', loginAdminSub:'সিস্টেম ব্যবস্থাপনা',
    loginUsername:'ব্যবহারকারীর নাম', loginPassword:'পাসওয়ার্ড',
    loginUserPh:'ব্যবহারকারীর নাম লিখুন', loginPassPh:'পাসওয়ার্ড লিখুন',
    loginSubmit:'এগিয়ে যান', loginLoading:'সাইন ইন হচ্ছে…',
    loginDemo:'ডেমো মোড — যেকোনো নাম ও পাসওয়ার্ড',
    loginErrorFill:'অনুগ্রহ করে সব ক্ষেত্র পূরণ করুন', loginErrorInvalid:'ভুল তথ্য',
    logout:'বের হন',
    dbError:'ডেটাবেস ত্রুটি। পৃষ্ঠা রিফ্রেশ করুন।',
    consultationTitle:'পরামর্শ', noConnectionMsg:'রোগীর সাথে সংযুক্ত হলে পরামর্শ পাওয়া যাবে।',
    low:'কম গুরুতর', medium:'মাঝারি গুরুতর', high:'অত্যন্ত গুরুতর',
    patientName:'রোগীর নাম', ageFull:'বয়স', genderFull:'লিঙ্গ', recorded:'রেকর্ড',
  },
  ta: {
    registerPatient:'நோயாளி பதிவு', vitalsAndTriage:'உடல் அளவீடு',
    patientList:'நோயாளி பட்டியல்', consultation:'ஆலோசனை', aiSymptomChecker:'AI அறிகுறி சோதனை',
    writePrescription:'மருந்துச் சீட்டு எழுதுக', prescriptionHistory:'மருந்துச் சீட்டு வரலாறு',
    aiTriage:'AI மருத்துவ மதிப்பீடு', prescriptions:'மருந்துச் சீட்டுகள்', reminders:'நினைவூட்டல்கள்',
    consultDoctor:'மருத்துவர் ஆலோசனை', healthRecords:'சுகாதார பதிவுகள்',
    ashaTitle:'ஆஷா தொழிலாளர் டாஷ்போர்டு', doctorTitle:'மருத்துவர் டாஷ்போர்டு', adminTitle:'நிர்வாகி பேனல்',
    totalPatients:'மொத்த நோயாளிகள்', pendingSync:'காத்திருக்கும் ஒத்திசைவு',
    registeredToday:'இன்று பதிவானோர்', syncStatus:'ஒத்திசைவு நிலை',
    upToDate:'புதுப்பிக்கப்பட்டது', pending:'நிலுவையில்',
    syncNow:'இப்போது ஒத்திசை', syncing:'ஒத்திசைக்கிறது...', allSynced:'அனைத்தும் ஒத்திசைக்கப்பட்டது',
    recordsPendingSync:'பதிவுகள் ஒத்திசைவு நிலுவையில்',
    registerNewPatient:'புதிய நோயாளியை பதிவு செய்க', fullName:'முழு பெயர்',
    age:'வயது', gender:'பாலினம்', selectGender:'பாலினம் தேர்ந்தெடு',
    male:'ஆண்', female:'பெண்', other:'மற்றவர்',
    phone:'தொலைபேசி', address:'முகவரி', addressOptional:'முழு முகவரி (விருப்பம்)',
    villageArea:'கிராமம் / பகுதி', registerBtn:'நோயாளியை பதிவு செய்க',
    initializing:'தரவுத்தளம் தொடங்குகிறது...', saving:'சேமிக்கிறது...',
    recentRegistrations:'சமீபத்திய பதிவுகள்', noPatientsYet:'இன்னும் நோயாளிகள் இல்லை',
    patientSavedOk:'நோயாளி வெற்றிகரமாக பதிவு செய்யப்பட்டார்.',
    recordVitals:'உடல் அளவீடு பதிவு', selectPatient:'நோயாளியை தேர்ந்தெடு',
    tempF:'வெப்பநிலை (°F)', heartRate:'இதய துடிப்பு (bpm)',
    bpSystolic:'BP சிஸ்டோலிக்', bpDiastolic:'BP டையாஸ்டோலிக்',
    symptoms:'அறிகுறிகள்', symptomsPlaceholder:'அறிகுறிகளை விவரிக்கவும்...',
    runTriage:'மதிப்பீடு இயக்கு', triageResult:'AI மதிப்பீடு முடிவு',
    submitVitalsFirst:'முடிவு காண அளவீடுகளை சமர்ப்பிக்கவும்',
    vitalsSavedOk:'அளவீடு சேமிக்கப்பட்டது.',
    allPatients:'அனைத்து நோயாளிகள்', name:'பெயர்', ageGender:'வயது / பாலினம்',
    village:'கிராமம்', status:'நிலை', registered:'பதிவு செய்யப்பட்டது',
    synced:'ஒத்திசைக்கப்பட்டது', local:'உள்ளூர்',
    vitalsRecorded:'அளவீடுகள் பதிவு', writtenToday:'இன்று எழுதப்பட்டது',
    writePrescriptionTitle:'மருந்துச் சீட்டு எழுது',
    patientLabel:'நோயாளி', diagnosis:'நோய் கண்டறிதல்',
    prescriptionFreeText:'மருந்துச் சீட்டு (சுதந்திர உரை)', additionalNotes:'கூடுதல் குறிப்புகள்',
    extraInstructions:'கூடுதல் வழிமுறைகள்...',
    parseWithAI:'AI மூலம் பகுப்பாய்வு', structuredPreview:'கட்டமைக்கப்பட்ட முன்னோட்டம்',
    savePrescription:'மருந்துச் சீட்டை சேமி', clear:'அழி',
    parseFirst:'மருந்துச் சீட்டை உள்ளிட்டு AI பகுப்பாய்வு கிளிக் செய்யவும்',
    prescriptionSavedOk:'மருந்துச் சீட்டு சேமிக்கப்பட்டது.',
    prescriptionHistory2:'மருந்துச் சீட்டு வரலாறு', medicines:'மருந்துகள்', date:'தேதி',
    noTriageYet:'இன்னும் அளவீடுகள் இல்லை.', noPrescrYet:'இன்னும் மருந்துச் சீட்டு இல்லை',
    prescriptionWritten:'மருந்துச் சீட்டு எழுதப்பட்டது',
    welcomeBack:'வரவேற்கிறோம்', pending2:'இன்று நிலுவை', completed:'முடிந்தது', activeMeds:'செயலில் மருந்துகள்',
    yourPrescriptions:'உங்கள் மருந்துச் சீட்டுகள்', noPrescrPatient:'இன்னும் மருந்துச் சீட்டு இல்லை',
    noPrescrSub:'உங்கள் மருத்துவர் இங்கே சேர்ப்பார்கள்', listenAll:'அனைத்தையும் கேளுங்கள்',
    medicineReminders:'மருந்து நினைவூட்டல்கள்', noReminders:'நினைவூட்டல்கள் இல்லை',
    noReminderSub:'மருந்துச் சீட்டுகளிலிருந்து நினைவூட்டல்கள் உருவாக்கப்படுகின்றன',
    enableNotif:'அறிவிப்புகளை இயக்கு', notifActive:'அறிவிப்புகள் செயலில்',
    markTaken:'எடுத்துக்கொண்டேன்', taken:'எடுக்கப்பட்டது',
    prescribedBy:'பரிந்துரைத்தவர்',
    speakIntro:'உங்கள் மருந்துச் சீட்டில் பின்வரும் மருந்துகள் உள்ளன.',
    speakMed:'மருந்து', speakTake:'எடுக்கவும்', speakTiming:'நேரம்', speakFor:'காலம்', speakNext:'அடுத்தது',
    loginTitle:'கிராம்ஹெல்த்', loginSub:'லைட்',
    loginTagline:'கிராமப்புற சுகாதார தளம் — நோயாளிகள், ஆஷா தொழிலாளர்கள் & மருத்துவர்களை இணைக்கிறது.',
    loginSignin:'உள்நுழை', loginSelectRole:'உங்கள் பங்கை தேர்ந்தெடுக்கவும்',
    loginPatient:'நோயாளி', loginPatientSub:'மருந்துச் சீட்டு பார்க்கவும்',
    loginAsha:'ஆஷா தொழிலாளர்', loginAshaSub:'நோயாளி பதிவு',
    loginDoctor:'மருத்துவர்', loginDoctorSub:'மருந்துச் சீட்டு எழுதவும்',
    loginAdmin:'நிர்வாகி', loginAdminSub:'கணினி மேலாண்மை',
    loginUsername:'பயனர் பெயர்', loginPassword:'கடவுச்சொல்',
    loginUserPh:'பயனர் பெயரை உள்ளிடவும்', loginPassPh:'கடவுச்சொல்லை உள்ளிடவும்',
    loginSubmit:'தொடர்க', loginLoading:'உள்நுழைகிறது…',
    loginDemo:'டெமோ பயன்முறை — எந்த பெயரும் கடவுச்சொல்லும்',
    loginErrorFill:'அனைத்து புலங்களையும் நிரப்பவும்', loginErrorInvalid:'தவறான நற்சான்றிதழ்கள்',
    logout:'வெளியேறு',
    dbError:'தரவுத்தள பிழை. பக்கத்தை புதுப்பிக்கவும்.',
    consultationTitle:'ஆலோசனை', noConnectionMsg:'நோயாளியுடன் இணைந்தால் ஆலோசனை கிடைக்கும்.',
    low:'குறைந்த முன்னுரிமை', medium:'நடுத்தர முன்னுரிமை', high:'அதிக முன்னுரிமை',
    patientName:'நோயாளி பெயர்', ageFull:'வயது', genderFull:'பாலினம்', recorded:'பதிவு செய்யப்பட்டது',
  },
  te: {
    registerPatient:'రోగి నమోదు', vitalsAndTriage:'వైటల్స్ & ట్రయాజ్',
    patientList:'రోగుల జాబితా', consultation:'సంప్రదింపు', aiSymptomChecker:'AI లక్షణ తనిఖీ',
    writePrescription:'ప్రిస్క్రిప్షన్ రాయండి', prescriptionHistory:'ప్రిస్క్రిప్షన్ చరిత్ర',
    aiTriage:'AI ట్రయాజ్', prescriptions:'ప్రిస్క్రిప్షన్లు', reminders:'రిమైండర్లు',
    consultDoctor:'డాక్టర్ సంప్రదింపు', healthRecords:'ఆరోగ్య రికార్డులు',
    ashaTitle:'ఆశా వర్కర్ డాష్‌బోర్డ్', doctorTitle:'డాక్టర్ డాష్‌బోర్డ్', adminTitle:'అడ్మిన్ పేనల్',
    totalPatients:'మొత్తం రోగులు', pendingSync:'పెండింగ్ సింక్',
    registeredToday:'ఈరోజు నమోదు', syncStatus:'సింక్ స్థితి',
    upToDate:'అప్‌డేట్ ఉంది', pending:'పెండింగ్',
    syncNow:'ఇప్పుడు సింక్ చేయండి', syncing:'సింక్ అవుతోంది...', allSynced:'అన్నీ సింక్ అయ్యాయి',
    recordsPendingSync:'రికార్డులు సింక్ పెండింగ్',
    registerNewPatient:'కొత్త రోగిని నమోదు చేయండి', fullName:'పూర్తి పేరు',
    age:'వయస్సు', gender:'లింగం', selectGender:'లింగం ఎంచుకోండి',
    male:'పురుషుడు', female:'స్త్రీ', other:'ఇతర',
    phone:'ఫోన్', address:'చిరునామా', addressOptional:'పూర్తి చిరునామా (ఐచ్ఛికం)',
    villageArea:'గ్రామం / ప్రాంతం', registerBtn:'రోగిని నమోదు చేయండి',
    initializing:'డేటాబేస్ ప్రారంభమవుతోంది...', saving:'సేవ్ అవుతోంది...',
    recentRegistrations:'ఇటీవలి నమోదులు', noPatientsYet:'ఇంకా రోగులు లేరు',
    patientSavedOk:'రోగి విజయవంతంగా నమోదు అయ్యారు.',
    recordVitals:'వైటల్స్ రికార్డ్ చేయండి', selectPatient:'రోగిని ఎంచుకోండి',
    tempF:'ఉష్ణోగ్రత (°F)', heartRate:'హృదయ స్పందన (bpm)',
    bpSystolic:'BP సిస్టోలిక్', bpDiastolic:'BP డయాస్టోలిక్',
    symptoms:'లక్షణాలు', symptomsPlaceholder:'లక్షణాలు వివరించండి...',
    runTriage:'ట్రయాజ్ నిర్వహించండి', triageResult:'AI ట్రయాజ్ ఫలితం',
    submitVitalsFirst:'ఫలితం చూడటానికి వైటల్స్ సమర్పించండి',
    vitalsSavedOk:'వైటల్స్ సేవ్ అయ్యాయి.',
    allPatients:'అందరు రోగులు', name:'పేరు', ageGender:'వయస్సు / లింగం',
    village:'గ్రామం', status:'స్థితి', registered:'నమోదు',
    synced:'సింక్ అయింది', local:'స్థానిక',
    vitalsRecorded:'వైటల్స్ రికార్డ్', writtenToday:'ఈరోజు రాశారు',
    writePrescriptionTitle:'ప్రిస్క్రిప్షన్ రాయండి',
    patientLabel:'రోగి', diagnosis:'రోగ నిర్ధారణ',
    prescriptionFreeText:'ప్రిస్క్రిప్షన్ (స్వేచ్ఛా వచనం)', additionalNotes:'అదనపు నోట్స్',
    extraInstructions:'అదనపు సూచనలు...',
    parseWithAI:'AI తో విశ్లేషించండి', structuredPreview:'నిర్మాణాత్మక ప్రివ్యూ',
    savePrescription:'ప్రిస్క్రిప్షన్ సేవ్ చేయండి', clear:'క్లియర్',
    parseFirst:'ప్రిస్క్రిప్షన్ టైప్ చేసి AI తో విశ్లేషించండి క్లిక్ చేయండి',
    prescriptionSavedOk:'ప్రిస్క్రిప్షన్ సేవ్ అయింది.',
    prescriptionHistory2:'ప్రిస్క్రిప్షన్ చరిత్ర', medicines:'మందులు', date:'తేదీ',
    noTriageYet:'ఇంకా వైటల్స్ లేవు.', noPrescrYet:'ఇంకా ప్రిస్క్రిప్షన్లు లేవు',
    prescriptionWritten:'ప్రిస్క్రిప్షన్ రాశారు',
    welcomeBack:'స్వాగతం', pending2:'ఈరోజు పెండింగ్', completed:'పూర్తయింది', activeMeds:'యాక్టివ్ మందులు',
    yourPrescriptions:'మీ ప్రిస్క్రిప్షన్లు', noPrescrPatient:'ఇంకా ప్రిస్క్రిప్షన్లు లేవు',
    noPrescrSub:'మీ డాక్టర్ ఇక్కడ జోడిస్తారు', listenAll:'అన్నీ వినండి',
    medicineReminders:'మందు రిమైండర్లు', noReminders:'రిమైండర్లు లేవు',
    noReminderSub:'ప్రిస్క్రిప్షన్ల నుండి రిమైండర్లు తయారవుతాయి',
    enableNotif:'నోటిఫికేషన్లు ప్రారంభించు', notifActive:'నోటిఫికేషన్లు యాక్టివ్',
    markTaken:'తీసుకున్నాను', taken:'తీసుకున్నారు',
    prescribedBy:'సూచించిన వారు',
    speakIntro:'మీ ప్రిస్క్రిప్షన్‌లో కింది మందులు ఉన్నాయి.',
    speakMed:'మందు', speakTake:'తీసుకోండి', speakTiming:'సమయం', speakFor:'కోసం', speakNext:'తదుపరి',
    loginTitle:'గ్రామ్‌హెల్త్', loginSub:'లైట్',
    loginTagline:'గ్రామీణ ఆరోగ్య వేదిక — రోగులు, ఆశ కార్యకర్తలు & వైద్యులను కలుపుతుంది.',
    loginSignin:'సైన్ ఇన్', loginSelectRole:'మీ పాత్రను ఎంచుకోండి',
    loginPatient:'రోగి', loginPatientSub:'ప్రిస్క్రిప్షన్‌లు చూడండి',
    loginAsha:'ఆశా వర్కర్', loginAshaSub:'రోగులను నమోదు చేయండి',
    loginDoctor:'డాక్టర్', loginDoctorSub:'ప్రిస్క్రిప్షన్లు రాయండి',
    loginAdmin:'నిర్వాహకుడు', loginAdminSub:'సిస్టమ్ నిర్వహణ',
    loginUsername:'వినియోగదారు పేరు', loginPassword:'పాస్‌వర్డ్',
    loginUserPh:'వినియోగదారు పేరు నమోదు చేయండి', loginPassPh:'పాస్‌వర్డ్ నమోదు చేయండి',
    loginSubmit:'కొనసాగించు', loginLoading:'సైన్ ఇన్ అవుతోంది…',
    loginDemo:'డెమో మోడ్ — ఏ పేరు & పాస్‌వర్డ్ అయినా',
    loginErrorFill:'దయచేసి అన్ని ఫీల్డ్‌లు పూరించండి', loginErrorInvalid:'తప్పు వివరాలు',
    logout:'బయటకు',
    dbError:'డేటాబేస్ లోపం. పేజీని రిఫ్రెష్ చేయండి.',
    consultationTitle:'సంప్రదింపు', noConnectionMsg:'రోగితో కనెక్ట్ అయినప్పుడు సంప్రదింపు అందుబాటులో ఉంటుంది.',
    low:'తక్కువ ప్రాధాన్యత', medium:'మధ్యస్థ ప్రాధాన్యత', high:'అధిక ప్రాధాన్యత',
    patientName:'రోగి పేరు', ageFull:'వయస్సు', genderFull:'లింగం', recorded:'రికార్డ్',
  },
  mr: {
    registerPatient:'रुग्ण नोंदणी', vitalsAndTriage:'महत्त्वाची माहिती',
    patientList:'रुग्ण यादी', consultation:'सल्ला',
    writePrescription:'नुस्खा लिहा', prescriptionHistory:'नुस्खा इतिहास',
    aiTriage:'AI ट्रायेज', prescriptions:'नुस्खे', reminders:'आठवण',
    consultDoctor:'डॉक्टरांशी सल्लामसलत', healthRecords:'आरोग्य नोंदी',
    ashaTitle:'आशा कार्यकर्ता डॅशबोर्ड', doctorTitle:'डॉक्टर डॅशबोर्ड', adminTitle:'प्रशासक पॅनेल',
    totalPatients:'एकूण रुग्ण', pendingSync:'प्रलंबित सिंक', registeredToday:'आज नोंदणी',
    syncStatus:'सिंक स्थिती', upToDate:'अद्यतनित', pending:'प्रलंबित',
    syncNow:'आत्ता सिंक करा', syncing:'सिंक होत आहे...', allSynced:'सर्व सिंक झाले',
    recordsPendingSync:'नोंदी सिंक प्रलंबित',
    registerNewPatient:'नवीन रुग्ण नोंदणी', fullName:'पूर्ण नाव',
    age:'वय', gender:'लिंग', selectGender:'लिंग निवडा',
    male:'पुरुष', female:'स्त्री', other:'इतर',
    phone:'फोन', address:'पत्ता', addressOptional:'पूर्ण पत्ता (पर्यायी)',
    villageArea:'गाव / परिसर', registerBtn:'रुग्ण नोंदणी करा',
    initializing:'डेटाबेस सुरू होत आहे...', saving:'जतन होत आहे...',
    recentRegistrations:'अलीकडील नोंदणी', noPatientsYet:'अद्याप रुग्ण नाही',
    patientSavedOk:'रुग्ण यशस्वीरित्या नोंदणी झाला.',
    recordVitals:'महत्त्वाची माहिती नोंदवा', selectPatient:'रुग्ण निवडा',
    tempF:'तापमान (°F)', heartRate:'हृदय गती (bpm)',
    bpSystolic:'BP सिस्टोलिक', bpDiastolic:'BP डायस्टोलिक',
    symptoms:'लक्षणे', symptomsPlaceholder:'लक्षणे सांगा...',
    runTriage:'ट्रायेज चालवा', triageResult:'AI ट्रायेज निकाल',
    submitVitalsFirst:'निकाल पाहण्यासाठी माहिती सादर करा',
    vitalsSavedOk:'माहिती जतन झाली व ट्रायेज पूर्ण.',
    allPatients:'सर्व रुग्ण', name:'नाव', ageGender:'वय / लिंग',
    village:'गाव', status:'स्थिती', registered:'नोंदणी',
    synced:'सिंक झाले', local:'स्थानिक',
    vitalsRecorded:'माहिती नोंदणी', writtenToday:'आज लिहिले',
    writePrescriptionTitle:'नुस्खा लिहा', patientLabel:'रुग्ण', diagnosis:'रोग निदान',
    prescriptionFreeText:'नुस्खा (मुक्त मजकूर)', additionalNotes:'अतिरिक्त नोट्स',
    extraInstructions:'अतिरिक्त सूचना...',
    parseWithAI:'AI ने विश्लेषण', structuredPreview:'संरचित पूर्वावलोकन',
    savePrescription:'नुस्खा जतन करा', clear:'साफ करा',
    parseFirst:'नुस्खा टाइप करा आणि AI विश्लेषण क्लिक करा',
    prescriptionSavedOk:'नुस्खा यशस्वीरित्या जतन झाला.',
    prescriptionHistory2:'नुस्खा इतिहास', medicines:'औषधे', date:'तारीख',
    noTriageYet:'अद्याप माहिती नाही.', noPrescrYet:'अद्याप नुस्खे नाहीत',
    prescriptionWritten:'नुस्खा लिहिला गेला',
    welcomeBack:'स्वागत आहे', pending2:'आज प्रलंबित', completed:'पूर्ण', activeMeds:'सक्रिय औषधे',
    yourPrescriptions:'तुमचे नुस्खे', noPrescrPatient:'अद्याप नुस्खे नाहीत',
    noPrescrSub:'तुमचे डॉक्टर येथे जोडतील', listenAll:'सर्व ऐका',
    medicineReminders:'औषध आठवण', noReminders:'आठवण नाही',
    noReminderSub:'नुस्ख्यांमधून आठवण तयार होतात',
    enableNotif:'सूचना सुरू करा', notifActive:'सूचना सक्रिय',
    markTaken:'घेतले', taken:'घेतले',
    prescribedBy:'लिहून दिले',
    speakIntro:'तुमच्या नुस्ख्यात खालील औषधे आहेत.',
    speakMed:'औषध', speakTake:'घ्या', speakTiming:'वेळ', speakFor:'साठी', speakNext:'पुढील',
    loginTitle:'ग्रामहेल्थ', loginSub:'लाईट',
    loginTagline:'ग्रामीण आरोग्य व्यासपीठ — रुग्ण, आशा कार्यकर्ता आणि डॉक्टरांना जोडते.',
    loginSignin:'साइन इन', loginSelectRole:'आपली भूमिका निवडा',
    loginPatient:'रुग्ण', loginPatientSub:'प्रिस्क्रिप्शन पहा',
    loginAsha:'आशा कार्यकर्ता', loginAshaSub:'रुग्ण नोंदणी',
    loginDoctor:'डॉक्टर', loginDoctorSub:'प्रिस्क्रिप्शन लिहा',
    loginAdmin:'प्रशासक', loginAdminSub:'सिस्टम व्यवस्थापन',
    loginUsername:'वापरकर्ता नाव', loginPassword:'पासवर्ड',
    loginUserPh:'वापरकर्ता नाव प्रविष्ट करा', loginPassPh:'पासवर्ड प्रविष्ट करा',
    loginSubmit:'पुढे जा', loginLoading:'साइन इन होत आहे…',
    loginDemo:'डेमो मोड — कोणतेही नाव आणि पासवर्ड',
    loginErrorFill:'कृपया सर्व फील्ड भरा', loginErrorInvalid:'अवैध माहिती',
    logout:'बाहेर',
    dbError:'डेटाबेस त्रुटी. पृष्ठ रिफ्रेश करा.',
    consultationTitle:'सल्ला', noConnectionMsg:'रुग्णाशी कनेक्ट झाल्यावर सल्ला उपलब्ध होईल.',
    low:'कमी प्राधान्य', medium:'मध्यम प्राधान्य', high:'उच्च प्राधान्य',
    patientName:'रुग्णाचे नाव', ageFull:'वय', genderFull:'लिंग', recorded:'नोंदणी',
  },
};

// ── First Aid translations ───────────────────────────────────────────
const FIRSTAID = {
  en: {
    videoCall:'📹 Video Call', firstAidNav:'🩹 First Aid', firstAidTitle:'Emergency Help & First Aid',
    firstAidSubtitle:'Offline-accessible guidance for common emergencies',
    disclaimer:'This guidance is for temporary support only. Seek professional medical care immediately in serious conditions.',
    voiceRead:'🔊 Read Aloud', voiceStop:'⏹ Stop',
    whatToDo:'What To Do', whatNotToDo:'What NOT To Do',
    goToHospital:'When To Go To Hospital', warningSigns:'Emergency Warning Signs',
    snakeBite:'Snake Bite', burns:'Burns', fever:'High Fever', dehydration:'Dehydration',
    diarrhea:'Diarrhea', fracture:'Minor Fracture', breathing:'Breathing Difficulty',
    snakeBite_do:['Keep the patient calm and still','Immobilize the affected limb below heart level','Remove tight clothing and jewellery near bite','Mark the bite site with a pen and note the time','Carry the patient — do not let them walk'],
    snakeBite_dont:['Do NOT cut or suck the wound','Do NOT apply ice or tourniquet','Do NOT give alcohol or painkillers','Do NOT let patient walk or run'],
    snakeBite_hospital:['Go to hospital immediately — do not wait','Anti-venom must be given within 4 hours','Any snake bite is a medical emergency'],
    snakeBite_warning:['Swelling spreading rapidly','Difficulty breathing or swallowing','Blurred vision or drooping eyelids','Vomiting or confusion'],
    burns_do:['Cool the burn with cool running water for 20 minutes','Cover loosely with a clean bandage or cloth','Give paracetamol for pain if available','Keep the patient warm to prevent shock'],
    burns_dont:['Do NOT use ice, butter, toothpaste or oil','Do NOT break blisters','Do NOT remove stuck clothing','Do NOT use fluffy cotton directly on burn'],
    burns_hospital:['Burns larger than palm of hand','Burns on face, hands, feet, genitals','Deep burns (skin looks white or charred)','Chemical or electrical burns — always'],
    burns_warning:['Burn turns white, brown or black','Patient loses sensation in burn area','Signs of infection: pus, fever, smell','Shock: pale skin, rapid breathing'],
    fever_do:['Give paracetamol as per age and weight','Ensure patient drinks plenty of fluids','Use wet cloth on forehead, armpits and neck','Rest in a cool, ventilated room','Monitor temperature every 2 hours'],
    fever_dont:['Do NOT give aspirin to children under 16','Do NOT wrap patient in thick blankets','Do NOT give two fever medicines together'],
    fever_hospital:['Fever above 103°F for more than 2 days','Fever with stiff neck or rash','Fever with convulsions','Infant under 3 months with any fever'],
    fever_warning:['Seizures or convulsions','Stiff neck or severe headache','Confusion or unresponsiveness','Rash that does not fade when pressed'],
    dehydration_do:['Give ORS frequently in small sips','Make home ORS: 1L water + 6 tsp sugar + half tsp salt','Give coconut water, rice water, or diluted fruit juice','Continue breastfeeding infants','Rest the patient'],
    dehydration_dont:['Do NOT give sweet fizzy drinks to infants alone','Do NOT give adult ORS to newborns without doctor advice','Do NOT stop ORS even if vomiting — give smaller sips'],
    dehydration_hospital:['No urine for more than 8 hours','Sunken eyes or fontanelle in infants','Patient cannot keep any fluid down','Extreme weakness or unconsciousness'],
    dehydration_warning:['No tears when crying','Very dry mouth and lips','Rapid heartbeat or weak pulse','Confusion or fainting'],
    diarrhea_do:['Start ORS immediately after each loose stool','Continue normal feeding and breastfeeding','Wash hands thoroughly before and after toilet','Keep the patient hydrated with clean water','Give zinc tablets to children (ask ASHA worker)'],
    diarrhea_dont:['Do NOT stop eating — continue light food','Do NOT give anti-diarrheal drugs to children under 5 without doctor advice','Do NOT use unboiled water'],
    diarrhea_hospital:['Blood or mucus in stool','More than 10 loose stools in a day','Signs of dehydration appear','Fever above 101°F with diarrhea'],
    diarrhea_warning:['Blood in stools','Severe abdominal pain and cramps','High fever with diarrhea','Signs of dehydration: no urine, dry mouth'],
    fracture_do:['Immobilize the injured area — do not move it','Support the limb with a makeshift splint (stick + cloth)','Apply ice pack wrapped in cloth to reduce swelling','Elevate the limb if possible','Give paracetamol for pain'],
    fracture_dont:['Do NOT try to straighten or set the bone','Do NOT move the patient if spine injury is suspected','Do NOT apply tight bandages that cut off circulation','Do NOT give food or drink if surgery may be needed'],
    fracture_hospital:['Any suspected fracture needs X-ray confirmation','Open fracture (bone visible through skin) — immediate','Fracture near a joint — urgent','Loss of sensation or movement below injury'],
    fracture_warning:['Bone visible through skin','Limb looks deformed or at odd angle','Numbness or tingling below injury','Severe swelling rapidly increasing'],
    breathing_do:['Sit the patient upright or lean slightly forward','Loosen any tight clothing around neck and chest','Open windows and doors for fresh air','Help use prescribed inhaler if available','Stay calm and reassure the patient'],
    breathing_dont:['Do NOT lay the patient flat on their back','Do NOT leave the patient alone','Do NOT give food or water during episode','Do NOT smoke near the patient'],
    breathing_hospital:['Breathing does not improve in 5-10 minutes','Lips or fingernails turning blue','Patient is exhausted from breathing effort','No inhaler available and patient has known asthma'],
    breathing_warning:['Lips or fingernails turning blue (cyanosis)','Cannot complete a sentence while breathing','Breathing rate very fast or very slow','Patient becomes unconscious'],
  },
  hi: {
    videoCall:'📹 वीडियो कॉल', firstAidNav:'🩹 प्राथमिक चिकित्सा', firstAidTitle:'आपातकालीन सहायता और प्राथमिक चिकित्सा',
    firstAidSubtitle:'सामान्य आपात स्थितियों के लिए ऑफलाइन मार्गदर्शन',
    disclaimer:'यह मार्गदर्शन केवल अस्थायी सहायता के लिए है। गंभीर स्थितियों में तुरंत चिकित्सा सहायता लें।',
    voiceRead:'🔊 ज़ोर से पढ़ें', voiceStop:'⏹ रोकें',
    whatToDo:'क्या करें', whatNotToDo:'क्या न करें',
    goToHospital:'अस्पताल कब जाएं', warningSigns:'आपातकालीन चेतावनी संकेत',
    snakeBite:'सांप का काटना', burns:'जलन', fever:'तेज बुखार', dehydration:'निर्जलीकरण',
    diarrhea:'दस्त', fracture:'हल्की हड्डी टूटना', breathing:'सांस लेने में कठिनाई',
    snakeBite_do:['मरीज़ को शांत और स्थिर रखें','काटे हुए अंग को हृदय से नीचे स्थिर रखें','काटे स्थान के पास के कपड़े और गहने हटाएं','काटे स्थान पर पेन से निशान लगाएं और समय नोट करें','मरीज़ को उठाकर ले जाएं — चलने न दें'],
    snakeBite_dont:['घाव को काटें या चूसें नहीं','बर्फ या टूर्निकेट न लगाएं','शराब या दर्दनिवारक दवा न दें','मरीज़ को चलने या दौड़ने न दें'],
    snakeBite_hospital:['तुरंत अस्पताल जाएं — इंतजार न करें','4 घंटे के भीतर एंटी-वेनम देना जरूरी है','हर सांप का काटना एक चिकित्सा आपातकाल है'],
    snakeBite_warning:['तेज़ी से फैलती सूजन','सांस लेने या निगलने में कठिनाई','धुंधली दृष्टि या आँखें झुकना','उल्टी या भ्रम'],
    burns_do:['20 मिनट तक ठंडे बहते पानी से जलन को ठंडा करें','साफ पट्टी से ढकें','दर्द के लिए पेरासिटामोल दें','मरीज़ को गर्म रखें'],
    burns_dont:['बर्फ, मक्खन, टूथपेस्ट या तेल न लगाएं','छाले न फोड़ें','चिपके कपड़े न हटाएं','रूई सीधे जलन पर न लगाएं'],
    burns_hospital:['हथेली से बड़ी जलन','चेहरे, हाथ, पैर, गुप्तांग पर जलन','गहरी जलन (त्वचा सफेद या काली)','रासायनिक या बिजली से जलन — हमेशा'],
    burns_warning:['जलन सफेद, भूरी या काली हो जाए','जलन क्षेत्र में संवेदना न हो','संक्रमण के संकेत: मवाद, बुखार','झटका: पीली त्वचा, तेज सांस'],
    fever_do:['आयु और वजन अनुसार पेरासिटामोल दें','खूब पानी पिलाएं','माथे, बगल और गर्दन पर गीला कपड़ा रखें','ठंडे, हवादार कमरे में आराम करें','हर 2 घंटे में तापमान जांचें'],
    fever_dont:['16 साल से कम उम्र के बच्चों को एस्पिरिन न दें','मोटे कंबल में न लपेटें','दो बुखार की दवाएं एक साथ न दें'],
    fever_hospital:['2 दिन से अधिक 103°F से ऊपर बुखार','बुखार के साथ गर्दन में अकड़न या चकत्ते','बुखार के साथ दौरे','3 महीने से कम उम्र के शिशु को कोई भी बुखार'],
    fever_warning:['दौरे पड़ना','गर्दन में अकड़न या तेज सिरदर्द','भ्रम या बेहोशी','दबाने पर न मिटने वाले चकत्ते'],
    dehydration_do:['थोड़ी-थोड़ी मात्रा में ORS बार-बार दें','घरेलू ORS: 1L पानी + 6 चम्मच चीनी + आधा चम्मच नमक','नारियल पानी, चावल का पानी दें','शिशुओं को स्तनपान जारी रखें','मरीज़ को आराम दें'],
    dehydration_dont:['शिशुओं को अकेले मीठे पेय न दें','नवजात को डॉक्टर की सलाह के बिना वयस्क ORS न दें','उल्टी होने पर भी ORS बंद न करें'],
    dehydration_hospital:['8 घंटे से अधिक पेशाब न आए','आंखें या तालु धंसी हों','कोई भी तरल पेय न पचे','अत्यधिक कमजोरी या बेहोशी'],
    dehydration_warning:['रोने पर आंसू न आएं','मुंह और होंठ बहुत सूखे हों','तेज या कमजोर नाड़ी','भ्रम या बेहोशी'],
    diarrhea_do:['हर दस्त के बाद ORS तुरंत शुरू करें','सामान्य भोजन और स्तनपान जारी रखें','शौचालय के पहले और बाद में हाथ धोएं','साफ पानी से पर्याप्त हाइड्रेशन बनाए रखें','बच्चों को जिंक की गोलियां दें'],
    diarrhea_dont:['खाना बंद न करें','5 साल से कम उम्र के बच्चों को डॉक्टर की सलाह के बिना दस्त रोधी दवा न दें','बिना उबाले पानी का उपयोग न करें'],
    diarrhea_hospital:['मल में खून या बलगम','दिन में 10 से अधिक दस्त','निर्जलीकरण के संकेत','दस्त के साथ 101°F से अधिक बुखार'],
    diarrhea_warning:['मल में खून','पेट में तेज दर्द और ऐंठन','दस्त के साथ तेज बुखार','निर्जलीकरण के संकेत'],
    fracture_do:['चोटिल हिस्से को स्थिर करें — हिलाएं नहीं','लकड़ी + कपड़े से अस्थायी स्प्लिंट बनाएं','सूजन कम करने के लिए कपड़े में लिपटी बर्फ लगाएं','अंग को ऊपर उठाएं यदि संभव हो','दर्द के लिए पेरासिटामोल दें'],
    fracture_dont:['हड्डी को सीधा या सेट करने की कोशिश न करें','रीढ़ की चोट का संदेह हो तो मरीज़ को न हिलाएं','तंग पट्टी न लगाएं','अगर सर्जरी संभव हो तो कुछ खाने-पीने को न दें'],
    fracture_hospital:['किसी भी संदिग्ध फ्रैक्चर के लिए X-ray जरूरी','खुला फ्रैक्चर — तुरंत','जोड़ के पास फ्रैक्चर — जल्दी','चोट के नीचे संवेदना या हलचल का अभाव'],
    fracture_warning:['त्वचा से हड्डी दिखना','अंग विकृत या असामान्य कोण पर हो','चोट के नीचे सुन्नपन या झनझनाहट','तेज बढ़ती सूजन'],
    breathing_do:['मरीज़ को सीधा बैठाएं या थोड़ा आगे झुकाएं','गर्दन और छाती के पास के कपड़े ढीले करें','ताजी हवा के लिए खिड़कियां और दरवाजे खोलें','यदि इनहेलर उपलब्ध हो तो दिलाएं','शांत रहें और मरीज़ को ढांढस बंधाएं'],
    breathing_dont:['मरीज़ को पीठ के बल न लिटाएं','मरीज़ को अकेला न छोड़ें','दौरे के दौरान खाना या पानी न दें','मरीज़ के पास धूम्रपान न करें'],
    breathing_hospital:['5-10 मिनट में सांस न सुधरे','होंठ या नाखून नीले पड़ जाएं','मरीज़ सांस लेने से थक जाए','इनहेलर न हो और मरीज़ को अस्थमा हो'],
    breathing_warning:['होंठ या नाखून नीले पड़ना','सांस लेते हुए पूरा वाक्य न बोल पाना','सांस बहुत तेज या बहुत धीमी','मरीज़ बेहोश हो जाए'],
  },
  ta: {
    videoCall:'📹 வீடியோ அழைப்பு', firstAidNav:'🩹 முதலுதவி', firstAidTitle:'அவசர உதவி மற்றும் முதலுதவி',
    firstAidSubtitle:'பொதுவான அவசரநிலைகளுக்கான ஆஃப்லைன் வழிகாட்டுதல்',
    disclaimer:'இந்த வழிகாட்டுதல் தற்காலிக ஆதரவுக்கு மட்டுமே. தீவிர நிலைமைகளில் உடனடியாக மருத்துவ உதவி தேடுங்கள்.',
    voiceRead:'🔊 சத்தமாகப் படிக்கவும்', voiceStop:'⏹ நிறுத்து',
    whatToDo:'என்ன செய்ய வேண்டும்', whatNotToDo:'என்ன செய்யக்கூடாது',
    goToHospital:'மருத்துவமனைக்கு எப்போது செல்ல வேண்டும்', warningSigns:'அவசர எச்சரிக்கை அறிகுறிகள்',
    snakeBite:'பாம்பு கடி', burns:'தீக்காயம்', fever:'அதிக காய்ச்சல்', dehydration:'நீர்ச்சத்து இழப்பு',
    diarrhea:'வயிற்றுப்போக்கு', fracture:'சிறிய எலும்பு முறிவு', breathing:'மூச்சு திணறல்',
    snakeBite_do:['நோயாளியை அமைதியாகவும் அசைவற்றும் வைக்கவும்','கடிபட்ட அங்கத்தை இதயத்திற்கு கீழ் நிலையில் வைக்கவும்','கடி இடத்திற்கு அருகில் இறுக்கமான ஆடை மற்றும் நகைகளை அகற்றவும்','கடி இடத்தில் பேனாவால் குறி வைத்து நேரத்தை குறிக்கவும்','நோயாளியை தூக்கிச் செல்லுங்கள் — நடக்க அனுமதிக்காதீர்கள்'],
    snakeBite_dont:['காயத்தை வெட்டவோ உறிஞ்சவோ வேண்டாம்','பனிக்கட்டி அல்லது இறுக்கக் கட்டு போடாதீர்கள்','ஆல்கஹால் அல்லது வலிநிவாரணிகள் கொடுக்காதீர்கள்','நோயாளியை நடக்க அல்லது ஓட அனுமதிக்காதீர்கள்'],
    snakeBite_hospital:['உடனடியாக மருத்துவமனைக்கு செல்லுங்கள்','4 மணி நேரத்திற்குள் நஞ்சு மருந்து கொடுக்க வேண்டும்','எந்த பாம்பு கடியும் ஒரு மருத்துவ அவசரநிலை'],
    snakeBite_warning:['வேகமாக பரவும் வீக்கம்','மூச்சு விடுவதில் சிரமம்','மங்கலான பார்வை அல்லது கண் இமை தொய்வு','வாந்தி அல்லது குழப்பம்'],
    burns_do:['20 நிமிடங்கள் குளிர்ந்த ஓடும் நீரில் காயத்தை குளிரவிடுங்கள்','சுத்தமான துணியால் இலகுவாக மூடுங்கள்','வலிக்கு பாராசிட்டமால் கொடுங்கள்','அதிர்ச்சி தடுக்க நோயாளியை சூடாக வைக்கவும்'],
    burns_dont:['பனிக்கட்டி, வெண்ணெய், பற்பசை அல்லது எண்ணெய் பயன்படுத்தாதீர்கள்','கொப்புளங்களை உடைக்காதீர்கள்','ஒட்டிய ஆடைகளை அகற்றாதீர்கள்','காயத்தில் நேரடியாக பஞ்சு போடாதீர்கள்'],
    burns_hospital:['உள்ளங்கையை விட பெரிய தீக்காயம்','முகம், கைகள், கால்கள் காயங்கள்','ஆழமான தீக்காயம்','வேதிப்பொருள் அல்லது மின்சார தீக்காயம்'],
    burns_warning:['காயம் வெள்ளை, பழுப்பு அல்லது கருப்பாக மாறும்','காயப்பட்ட இடத்தில் உணர்வு இல்லாமல் போகும்','தொற்று அறிகுறிகள்: சீழ், காய்ச்சல்','அதிர்ச்சி: வெளிர் சருமம்'],
    fever_do:['வயது மற்றும் எடைக்கு ஏற்ப பாராசிட்டமால் கொடுங்கள்','நிறைய திரவங்கள் குடிக்க உறுதி செய்யுங்கள்','நெற்றி, அக்குள் மற்றும் கழுத்தில் ஈரமான துணி வையுங்கள்','குளிரான, காற்றோட்டமான அறையில் ஓய்வெடுங்கள்','ஒவ்வொரு 2 மணி நேரத்திற்கும் வெப்பநிலையை கண்காணிக்கவும்'],
    fever_dont:['16 வயதுக்கு கீழ் குழந்தைகளுக்கு ஆஸ்பிரின் கொடுக்காதீர்கள்','தடிமனான போர்வைகளில் சுற்றாதீர்கள்','இரண்டு காய்ச்சல் மருந்துகளை ஒரே நேரத்தில் கொடுக்காதீர்கள்'],
    fever_hospital:['2 நாட்களுக்கும் மேல் 103°F க்கு மேல் காய்ச்சல்','கழுத்து இறுக்கம் அல்லது சொறி உள்ள காய்ச்சல்','வலிப்புடன் காய்ச்சல்','3 மாதங்களுக்கு கீழ் உள்ள குழந்தைக்கு காய்ச்சல்'],
    fever_warning:['வலிப்பு','கழுத்து இறுக்கம் அல்லது கடுமையான தலைவலி','குழப்பம் அல்லது உணர்வின்மை','அழுத்தும்போது மறையாத சொறி'],
    dehydration_do:['சிறிய சிப்களில் அடிக்கடி ORS கொடுங்கள்','வீட்டு ORS: 1L நீர் + 6 ஸ்பூன் சர்க்கரை + அரை ஸ்பூன் உப்பு','தேங்காய் நீர், அரிசி நீர் கொடுங்கள்','குழந்தைகளுக்கு தொடர்ந்து தாய்ப்பால் கொடுங்கள்','நோயாளியை ஓய்வெடுக்க அனுமதியுங்கள்'],
    dehydration_dont:['குழந்தைகளுக்கு மட்டும் இனிப்பு பானங்கள் கொடுக்காதீர்கள்','மருத்துவர் ஆலோசனையின்றி வயு வந்தோர் ORS கொடுக்காதீர்கள்','வாந்தி வந்தாலும் ORS நிறுத்தாதீர்கள்'],
    dehydration_hospital:['8 மணி நேரத்திற்கும் மேல் சிறுநீர் இல்லை','குழந்தைகளில் கண்கள் உள்ளே போதல்','எந்த திரவமும் வயிற்றில் இருக்காவிட்டால்','கடுமையான சோர்வு அல்லது சுயநினைவின்மை'],
    dehydration_warning:['அழும்போது கண்ணீர் இல்லை','வாய் மற்றும் உதடுகள் மிகவும் உலர்ந்திருக்கும்','வேகமான இதயத்துடிப்பு அல்லது பலவீனமான நாடி','குழப்பம் அல்லது மயக்கம்'],
    diarrhea_do:['ஒவ்வொரு தளர்வான மலத்திற்கும் பிறகு உடனடியாக ORS தொடங்குங்கள்','சாதாரண உணவு மற்றும் தாய்ப்பால் தொடரவும்','கழிவறைக்கு முன்னும் பின்னும் கைகளை நன்றாக கழுவுங்கள்','சுத்தமான நீரில் நோயாளியை நீரேற்றமாக வைக்கவும்','குழந்தைகளுக்கு ஜிங்க் மாத்திரைகள் கொடுங்கள்'],
    diarrhea_dont:['சாப்பிடுவதை நிறுத்தாதீர்கள்','5 வயதுக்கு கீழ் குழந்தைகளுக்கு வயிற்றுப்போக்கு மருந்து கொடுக்காதீர்கள்','கொதிக்காத நீரை பயன்படுத்தாதீர்கள்'],
    diarrhea_hospital:['மலத்தில் இரத்தம் அல்லது சளி','ஒரு நாளில் 10 க்கும் மேல் தளர்வான மலம்','நீர்ச்சத்து இழப்பு அறிகுறிகள் தோன்றும்','வயிற்றுப்போக்குடன் 101°F க்கும் மேல் காய்ச்சல்'],
    diarrhea_warning:['மலத்தில் இரத்தம்','கடுமையான வயிற்று வலி மற்றும் பிடிப்பு','வயிற்றுப்போக்குடன் அதிக காய்ச்சல்','நீர்ச்சத்து இழப்பு அறிகுறிகள்'],
    fracture_do:['காயமடைந்த பகுதியை அசைக்காமல் நிலைப்படுத்துங்கள்','குச்சி + துணியால் தற்காலிக ஆதரவு கட்டு கட்டுங்கள்','வீக்கத்தை குறைக்க துணியில் சுற்றிய பனிக்கட்டி வையுங்கள்','முடிந்தால் கை/காலை உயரமாக வையுங்கள்','வலிக்கு பாராசிட்டமால் கொடுங்கள்'],
    fracture_dont:['எலும்பை நேராக்க முயற்சிக்காதீர்கள்','முதுகெலும்பு காயம் சந்தேகிக்கப்பட்டால் நோயாளியை நகர்த்தாதீர்கள்','இரத்த ஓட்டத்தை தடுக்கும் இறுக்கமான கட்டுகள் போடாதீர்கள்','அறுவை சிகிச்சை தேவைப்படலாம் என்றால் சாப்பிட கொடுக்காதீர்கள்'],
    fracture_hospital:['எந்த சந்தேகமான எலும்பு முறிவிற்கும் X-ray தேவை','திறந்த எலும்பு முறிவு — உடனடி','மூட்டிற்கு அருகில் எலும்பு முறிவு — அவசரம்','காயத்திற்கு கீழ் உணர்வு இல்லாமல் போதல்'],
    fracture_warning:['சருமத்தின் வழியாக எலும்பு தெரிதல்','கை/கால் திரிந்த கோணத்தில் இருத்தல்','காயத்திற்கு கீழ் உணர்வின்மை அல்லது சுர்சுர்ப்பு','வேகமாக அதிகரிக்கும் கடுமையான வீக்கம்'],
    breathing_do:['நோயாளியை நேராக உட்கார வைக்கவும்','கழுத்து மற்றும் மார்பு பகுதியில் இறுக்கமான ஆடைகளை தளர்த்தவும்','புதிய காற்றுக்கு ஜன்னல்கள் மற்றும் கதவுகளை திறக்கவும்','இன்ஹேலர் கிடைத்தால் உதவுங்கள்','அமைதியாக இருங்கள் மற்றும் நோயாளியை ஆற்றுங்கள்'],
    breathing_dont:['நோயாளியை மல்லாந்து படுக்க வைக்காதீர்கள்','நோயாளியை தனியாக விடாதீர்கள்','வலிப்பின் போது உணவு அல்லது நீர் கொடுக்காதீர்கள்','நோயாளி அருகில் புகைபிடிக்காதீர்கள்'],
    breathing_hospital:['5-10 நிமிடங்களில் சுவாசம் சரியாகவில்லை என்றால்','உதடுகள் அல்லது நகங்கள் நீல நிறமாக மாறினால்','நோயாளி சுவாசிப்பதால் மிகவும் சோர்வடைந்தால்','இன்ஹேலர் இல்லாமல் நோயாளிக்கு ஆஸ்துமா இருந்தால்'],
    breathing_warning:['உதடுகள் அல்லது நகங்கள் நீல நிறமாக மாறுதல்','சுவாசிக்கும்போது ஒரு வாக்கியத்தை முடிக்க முடியாமல் போதல்','சுவாச வீதம் மிகவும் வேகமாக அல்லது மெதுவாக','நோயாளி சுயநினைவை இழத்தல்'],
  },
  kn: {
    videoCall:'📹 ವಿಡಿಯೋ ಕರೆ', firstAidNav:'🩹 ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ', firstAidTitle:'ತುರ್ತು ಸಹಾಯ ಮತ್ತು ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ',
    loginTitle:'ಗ್ರಾಮ್‌ಹೆಲ್ತ್', loginSub:'ಲೈಟ್',
    loginTagline:'ಗ್ರಾಮೀಣ ಆರೋಗ್ಯ ವೇದಿಕೆ — ರೋಗಿಗಳು, ಆಶಾ ಕಾರ್ಯಕರ್ತರು & ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸುತ್ತದೆ.',
    loginSignin:'ಸೈನ್ ಇನ್', loginSelectRole:'ನಿಮ್ಮ ಪಾತ್ರ ಆಯ್ಕೆ ಮಾಡಿ',
    loginPatient:'ರೋಗಿ', loginPatientSub:'ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ನೋಡಿ',
    loginAsha:'ಆಶಾ ಕಾರ್ಯಕರ್ತ', loginAshaSub:'ರೋಗಿ ನೋಂದಣಿ',
    loginDoctor:'ವೈದ್ಯ', loginDoctorSub:'ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಬರೆಯಿರಿ',
    loginAdmin:'ನಿರ್ವಾಹಕ', loginAdminSub:'ಸಿಸ್ಟಮ್ ನಿರ್ವಹಣೆ',
    loginUsername:'ಬಳಕೆದಾರ ಹೆಸರು', loginPassword:'ಪಾಸ್‌ವರ್ಡ್',
    loginUserPh:'ಬಳಕೆದಾರ ಹೆಸರು ನಮೂದಿಸಿ', loginPassPh:'ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    loginSubmit:'ಮುಂದುವರಿಯಿರಿ', loginLoading:'ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ…',
    loginDemo:'ಡೆಮೊ ಮೋಡ್ — ಯಾವುದೇ ಹೆಸರು ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್',
    loginErrorFill:'ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಕ್ಷೇತ್ರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ', loginErrorInvalid:'ತಪ್ಪಾದ ರುಜುವಾತುಗಳು',
    logout:'ಹೊರಗೆ',
    firstAidSubtitle:'ಸಾಮಾನ್ಯ ತುರ್ತು ಪರಿಸ್ಥಿತಿಗಳಿಗೆ ಆಫ್‌ಲೈನ್ ಮಾರ್ಗದರ್ಶನ',
    disclaimer:'ಈ ಮಾರ್ಗದರ್ಶನವು ತಾತ್ಕಾಲಿಕ ಬೆಂಬಲಕ್ಕಾಗಿ ಮಾತ್ರ. ಗಂಭೀರ ಪರಿಸ್ಥಿತಿಗಳಲ್ಲಿ ತಕ್ಷಣ ವೈದ್ಯಕೀಯ ಆರೈಕೆ ಪಡೆಯಿರಿ.',
    voiceRead:'🔊 ಜೋರಾಗಿ ಓದಿ', voiceStop:'⏹ ನಿಲ್ಲಿಸಿ',
    whatToDo:'ಏನು ಮಾಡಬೇಕು', whatNotToDo:'ಏನು ಮಾಡಬಾರದು',
    goToHospital:'ಆಸ್ಪತ್ರೆಗೆ ಯಾವಾಗ ಹೋಗಬೇಕು', warningSigns:'ತುರ್ತು ಎಚ್ಚರಿಕೆ ಚಿಹ್ನೆಗಳು',
    snakeBite:'ಹಾವಿನ ಕಡಿತ', burns:'ಸುಡು ಗಾಯ', fever:'ತೀವ್ರ ಜ್ವರ', dehydration:'ನಿರ್ಜಲೀಕರಣ',
    diarrhea:'ಅತಿಸಾರ', fracture:'ಚಿಕ್ಕ ಮೂಳೆ ಮುರಿತ', breathing:'ಉಸಿರಾಟದ ತೊಂದರೆ',
    snakeBite_do:['ರೋಗಿಯನ್ನು ಶಾಂತವಾಗಿ ಮತ್ತು ಸ್ಥಿರವಾಗಿ ಇರಿಸಿ','ಕಡಿದ ಅಂಗವನ್ನು ಹೃದಯದ ಕೆಳಗೆ ಇರಿಸಿ','ಕಡಿದ ಸ್ಥಳದ ಬಳಿ ಬಿಗಿಯಾದ ಬಟ್ಟೆ ಮತ್ತು ಆಭರಣ ತೆಗೆಯಿರಿ','ಕಡಿದ ಸ್ಥಳದಲ್ಲಿ ಪೆನ್ನಿನಿಂದ ಗುರುತು ಮಾಡಿ','ರೋಗಿಯನ್ನು ಹೊತ್ತೊಯ್ಯಿರಿ — ನಡೆಯಲು ಬಿಡಬೇಡಿ'],
    snakeBite_dont:['ಗಾಯವನ್ನು ಕತ್ತರಿಸಬೇಡಿ ಅಥವಾ ಹೀರಬೇಡಿ','ಐಸ್ ಅಥವಾ ಟೂರ್ನಿಕೆಟ್ ಹಾಕಬೇಡಿ','ಮದ್ಯ ಅಥವಾ ನೋವು ನಿವಾರಕ ಕೊಡಬೇಡಿ','ರೋಗಿಯನ್ನು ನಡೆಯಲು ಅಥವಾ ಓಡಲು ಬಿಡಬೇಡಿ'],
    snakeBite_hospital:['ತಕ್ಷಣ ಆಸ್ಪತ್ರೆಗೆ ಹೋಗಿ','4 ಗಂಟೆಗಳೊಳಗೆ ಆಂಟಿ-ವೆನಮ್ ನೀಡಬೇಕು','ಯಾವುದೇ ಹಾವಿನ ಕಡಿತ ವೈದ್ಯಕೀಯ ತುರ್ತು'],
    snakeBite_warning:['ವೇಗವಾಗಿ ಹರಡುವ ಊತ','ಉಸಿರಾಡಲು ಅಥವಾ ನುಂಗಲು ತೊಂದರೆ','ಮಸುಕಾದ ದೃಷ್ಟಿ ಅಥವಾ ಕಣ್ಣು ತಗ್ಗುವುದು','ವಾಂತಿ ಅಥವಾ ಗೊಂದಲ'],
    burns_do:['20 ನಿಮಿಷ ತಂಪು ಹರಿಯುವ ನೀರಿನಿಂದ ತಣ್ಣಗಾಗಿಸಿ','ಸ್ವಚ್ಛ ಬ್ಯಾಂಡೇಜ್‌ನಿಂದ ಸಡಿಲವಾಗಿ ಮುಚ್ಚಿ','ನೋವಿಗೆ ಪ್ಯಾರಸಿಟಮಾಲ್ ಕೊಡಿ','ಶಾಕ್ ತಡೆಯಲು ರೋಗಿಯನ್ನು ಬೆಚ್ಚಗಿರಿಸಿ'],
    burns_dont:['ಐಸ್, ಬೆಣ್ಣೆ, ಟೂತ್‌ಪೇಸ್ಟ್ ಅಥವಾ ಎಣ್ಣೆ ಬಳಸಬೇಡಿ','ಗುಳ್ಳೆಗಳನ್ನು ಒಡೆಯಬೇಡಿ','ಅಂಟಿಕೊಂಡ ಬಟ್ಟೆ ತೆಗೆಯಬೇಡಿ','ಗಾಯದ ಮೇಲೆ ನೇರವಾಗಿ ಹತ್ತಿ ಹಾಕಬೇಡಿ'],
    burns_hospital:['ಅಂಗೈಗಿಂತ ದೊಡ್ಡ ಸುಡು ಗಾಯ','ಮುಖ, ಕೈ, ಕಾಲು ಗಾಯಗಳು','ಆಳವಾದ ಸುಡು ಗಾಯ','ರಾಸಾಯನಿಕ ಅಥವಾ ವಿದ್ಯುತ್ ಸುಡು ಗಾಯ'],
    burns_warning:['ಗಾಯ ಬಿಳಿ, ಕಂದು ಅಥವಾ ಕಪ್ಪಾಗುತ್ತದೆ','ಗಾಯದ ಪ್ರದೇಶದಲ್ಲಿ ಸಂವೇದನೆ ಇಲ್ಲ','ಸೋಂಕಿನ ಚಿಹ್ನೆಗಳು: ಕೀವು, ಜ್ವರ','ಶಾಕ್: ಮಂಕಾದ ಚರ್ಮ'],
    fever_do:['ವಯಸ್ಸು ಮತ್ತು ತೂಕಕ್ಕೆ ಅನುಗುಣವಾಗಿ ಪ್ಯಾರಸಿಟಮಾಲ್ ಕೊಡಿ','ಸಾಕಷ್ಟು ದ್ರವ ಕುಡಿಯಲು ಖಾತ್ರಿಪಡಿಸಿ','ಹಣೆ, ತೋಳ್ಕಂಕುಳ ಮತ್ತು ಕತ್ತಿನ ಮೇಲೆ ತೇವ ಬಟ್ಟೆ ಇಡಿ','ತಂಪು, ಗಾಳಿ ಬೀಸುವ ಕೊಠಡಿಯಲ್ಲಿ ವಿಶ್ರಾಂತಿ','ಪ್ರತಿ 2 ಗಂಟೆಗೆ ಉಷ್ಣಾಂಶ ಪರೀಕ್ಷಿಸಿ'],
    fever_dont:['16 ವರ್ಷದೊಳಗಿನ ಮಕ್ಕಳಿಗೆ ಆ್ಯಸ್ಪಿರಿನ್ ಕೊಡಬೇಡಿ','ದಪ್ಪ ಹೊದಿಕೆಗಳಲ್ಲಿ ಸುತ್ತಿಡಬೇಡಿ','ಒಟ್ಟಿಗೆ ಎರಡು ಜ್ವರದ ಮದ್ದು ಕೊಡಬೇಡಿ'],
    fever_hospital:['2 ದಿನಗಳಿಗಿಂತ ಹೆಚ್ಚು 103°F ಮೇಲೆ ಜ್ವರ','ಕತ್ತು ಬಿಗಿ ಅಥವಾ ಚಕ್ಕೆ ಸಮೇತ ಜ್ವರ','ಅಪಸ್ಮಾರದೊಂದಿಗೆ ಜ್ವರ','3 ತಿಂಗಳೊಳಗಿನ ಶಿಶುವಿಗೆ ಯಾವುದೇ ಜ್ವರ'],
    fever_warning:['ಅಪಸ್ಮಾರ ಅಥವಾ ಸೆಳವು','ಕತ್ತು ಬಿಗಿ ಅಥವಾ ತೀವ್ರ ತಲೆನೋವು','ಗೊಂದಲ ಅಥವಾ ಪ್ರತಿಕ್ರಿಯೆ ಇಲ್ಲದಿರುವುದು','ಒತ್ತಿದಾಗ ಮಾಯದ ಚಕ್ಕೆ'],
    dehydration_do:['ಸಣ್ಣ ಗುಟುಕಿನಲ್ಲಿ ಆಗಾಗ ORS ಕೊಡಿ','ಮನೆ ORS: 1L ನೀರು + 6 ಚಮಚ ಸಕ್ಕರೆ + ಅರ್ಧ ಚಮಚ ಉಪ್ಪು','ತೆಂಗಿನ ನೀರು, ಅಕ್ಕಿ ನೀರು ಕೊಡಿ','ಶಿಶುಗಳಿಗೆ ತಾಯಿಹಾಲು ಮುಂದುವರಿಸಿ','ರೋಗಿಯನ್ನು ವಿಶ್ರಾಂತಿ ತೆಗೆಯಲು ಬಿಡಿ'],
    dehydration_dont:['ಶಿಶುಗಳಿಗೆ ಒಂಟಿಯಾಗಿ ಸಿಹಿ ಪಾನೀಯ ಕೊಡಬೇಡಿ','ವೈದ್ಯರ ಸಲಹೆಯಿಲ್ಲದೆ ನವಜಾತ ಶಿಶುವಿಗೆ ORS ಕೊಡಬೇಡಿ','ವಾಂತಿ ಆದರೂ ORS ನಿಲ್ಲಿಸಬೇಡಿ'],
    dehydration_hospital:['8 ಗಂಟೆಗಿಂತ ಹೆಚ್ಚು ಮೂತ್ರ ಇಲ್ಲ','ಶಿಶುಗಳಲ್ಲಿ ಕಣ್ಣು ಒಳಕ್ಕೆ ಹೋಗುವುದು','ಯಾವುದೇ ದ್ರವ ಹೊಟ್ಟೆಯಲ್ಲಿ ಇರದಿದ್ದರೆ','ತೀವ್ರ ದೌರ್ಬಲ್ಯ ಅಥವಾ ಪ್ರಜ್ಞಾಹೀನತೆ'],
    dehydration_warning:['ಅಳುವಾಗ ಕಣ್ಣೀರು ಇಲ್ಲ','ಬಾಯಿ ಮತ್ತು ತುಟಿಗಳು ತುಂಬಾ ಒಣಗಿವೆ','ವೇಗದ ಹೃದಯ ಬಡಿತ ಅಥವಾ ದುರ್ಬಲ ನಾಡಿ','ಗೊಂದಲ ಅಥವಾ ಮೂರ್ಛೆ'],
    diarrhea_do:['ಪ್ರತಿ ಸಡಿಲ ಮಲದ ನಂತರ ತಕ್ಷಣ ORS ಪ್ರಾರಂಭಿಸಿ','ಸಾಮಾನ್ಯ ಆಹಾರ ಮತ್ತು ತಾಯಿಹಾಲು ಮುಂದುವರಿಸಿ','ಶೌಚಾಲಯಕ್ಕೆ ಮೊದಲು ಮತ್ತು ನಂತರ ಕೈ ತೊಳೆಯಿರಿ','ಶುದ್ಧ ನೀರಿನಿಂದ ರೋಗಿಗೆ ನೀರಾಂಶ ನೀಡಿ','ಮಕ್ಕಳಿಗೆ ಜಿಂಕ್ ಮಾತ್ರೆಗಳು ಕೊಡಿ'],
    diarrhea_dont:['ತಿನ್ನುವುದನ್ನು ನಿಲ್ಲಿಸಬೇಡಿ','5 ವರ್ಷದೊಳಗಿನ ಮಕ್ಕಳಿಗೆ ವೈದ್ಯರ ಸಲಹೆಯಿಲ್ಲದೆ ಅತಿಸಾರ ಮದ್ದು ಕೊಡಬೇಡಿ','ಕುದಿಸದ ನೀರನ್ನು ಬಳಸಬೇಡಿ'],
    diarrhea_hospital:['ಮಲದಲ್ಲಿ ರಕ್ತ ಅಥವಾ ಲೋಳೆ','ಒಂದು ದಿನದಲ್ಲಿ 10 ಕ್ಕಿಂತ ಹೆಚ್ಚು ಸಡಿಲ ಮಲ','ನಿರ್ಜಲೀಕರಣದ ಚಿಹ್ನೆಗಳು ಕಾಣಿಸಿಕೊಂಡರೆ','ಅತಿಸಾರದೊಂದಿಗೆ 101°F ಮೇಲೆ ಜ್ವರ'],
    diarrhea_warning:['ಮಲದಲ್ಲಿ ರಕ್ತ','ತೀವ್ರ ಹೊಟ್ಟೆ ನೋವು ಮತ್ತು ಸೆಳೆತ','ಅತಿಸಾರದೊಂದಿಗೆ ಹೆಚ್ಚಿನ ಜ್ವರ','ನಿರ್ಜಲೀಕರಣ ಚಿಹ್ನೆಗಳು'],
    fracture_do:['ಗಾಯಗೊಂಡ ಭಾಗವನ್ನು ನಿಶ್ಚಲಗೊಳಿಸಿ','ಕಡ್ಡಿ + ಬಟ್ಟೆಯಿಂದ ತಾತ್ಕಾಲಿಕ ಆಧಾರ ಕಟ್ಟಿ','ಊತ ಕಡಿಮೆ ಮಾಡಲು ಬಟ್ಟೆಯಲ್ಲಿ ಸುತ್ತಿದ ಐಸ್ ಹಾಕಿ','ಸಾಧ್ಯವಾದರೆ ಅಂಗವನ್ನು ಮೇಲೆ ಎತ್ತಿ','ನೋವಿಗೆ ಪ್ಯಾರಸಿಟಮಾಲ್ ಕೊಡಿ'],
    fracture_dont:['ಮೂಳೆಯನ್ನು ನೇರ ಮಾಡಲು ಪ್ರಯತ್ನಿಸಬೇಡಿ','ಬೆನ್ನುಮೂಳೆ ಗಾಯ ಶಂಕೆ ಇದ್ದರೆ ರೋಗಿಯನ್ನು ಚಲಿಸಬೇಡಿ','ರಕ್ತ ಪರಿಚಲನೆ ತಡೆಯುವ ಬಿಗಿ ಬ್ಯಾಂಡೇಜ್ ಹಾಕಬೇಡಿ','ಶಸ್ತ್ರಚಿಕಿತ್ಸೆ ಅಗತ್ಯ ಇದ್ದರೆ ತಿನ್ನಲು ಕೊಡಬೇಡಿ'],
    fracture_hospital:['ಯಾವುದೇ ಸಂಶಯಾಸ್ಪದ ಮೂಳೆ ಮುರಿತಕ್ಕೆ X-ray ಅಗತ್ಯ','ತೆರೆದ ಮೂಳೆ ಮುರಿತ — ತಕ್ಷಣ','ಕೀಲಿನ ಬಳಿ ಮೂಳೆ ಮುರಿತ — ತುರ್ತು','ಗಾಯದ ಕೆಳಗೆ ಸಂವೇದನೆ ಇಲ್ಲದಿರುವುದು'],
    fracture_warning:['ಚರ್ಮದ ಮೂಲಕ ಮೂಳೆ ಕಾಣಿಸುವುದು','ಅಂಗ ವಿರೂಪ ಅಥವಾ ಅಸಾಮಾನ್ಯ ಕೋನ','ಗಾಯದ ಕೆಳಗೆ ಮರಗಟ್ಟುವಿಕೆ ಅಥವಾ ಜುಮ್ಮೆನಿಸುವಿಕೆ','ತ್ವರಿತವಾಗಿ ಹೆಚ್ಚಾಗುವ ತೀವ್ರ ಊತ'],
    breathing_do:['ರೋಗಿಯನ್ನು ನೇರವಾಗಿ ಕುಳಿತುಕೊಳ್ಳಿಸಿ','ಕತ್ತು ಮತ್ತು ಎದೆ ಸುತ್ತ ಬಿಗಿಯಾದ ಬಟ್ಟೆ ಸಡಿಲ ಮಾಡಿ','ತಾಜಾ ಗಾಳಿಗಾಗಿ ಕಿಟಕಿ ಮತ್ತು ಬಾಗಿಲು ತೆರೆಯಿರಿ','ಇನ್‌ಹೇಲರ್ ಇದ್ದರೆ ಬಳಸಲು ಸಹಾಯ ಮಾಡಿ','ಶಾಂತವಾಗಿರಿ ಮತ್ತು ರೋಗಿಯನ್ನು ಧೈರ್ಯ ನೀಡಿ'],
    breathing_dont:['ರೋಗಿಯನ್ನು ಮಲಗಿಸಬೇಡಿ','ರೋಗಿಯನ್ನು ಒಂಟಿಯಾಗಿ ಬಿಡಬೇಡಿ','ಎಪಿಸೋಡ್ ಸಮಯದಲ್ಲಿ ಆಹಾರ ಅಥವಾ ನೀರು ಕೊಡಬೇಡಿ','ರೋಗಿ ಬಳಿ ಧೂಮಪಾನ ಮಾಡಬೇಡಿ'],
    breathing_hospital:['5-10 ನಿಮಿಷದಲ್ಲಿ ಉಸಿರಾಟ ಸುಧಾರಿಸದಿದ್ದರೆ','ತುಟಿ ಅಥವಾ ಉಗುರು ನೀಲಿ ಬಣ್ಣಕ್ಕೆ ತಿರುಗಿದರೆ','ರೋಗಿ ಉಸಿರಾಟದ ಪ್ರಯತ್ನದಿಂದ ದಣಿದಿದ್ದರೆ','ಇನ್‌ಹೇಲರ್ ಇಲ್ಲದೆ ರೋಗಿಗೆ ಆಸ್ತಮಾ ಇದ್ದರೆ'],
    breathing_warning:['ತುಟಿ ಅಥವಾ ಉಗುರು ನೀಲಿ ಬಣ್ಣಕ್ಕೆ ತಿರುಗುವುದು','ಉಸಿರಾಡುವಾಗ ಒಂದು ವಾಕ್ಯ ಮುಗಿಸಲಾಗದಿರುವುದು','ಉಸಿರಾಟದ ದರ ತುಂಬಾ ವೇಗ ಅಥವಾ ನಿಧಾನ','ರೋಗಿ ಪ್ರಜ್ಞೆ ಕಳೆದುಕೊಳ್ಳುವುದು'],
  },
};
Object.keys(FIRSTAID).forEach(lang => {
  if (!TRANSLATIONS[lang]) TRANSLATIONS[lang] = {};
  Object.assign(TRANSLATIONS[lang], FIRSTAID[lang]);
});

// Fill remaining languages with English fallback
['gu','kn','ml','pa','or','as','ur','mai','kok','doi','ne','sd','sat','mni','bodo','ks'].forEach(code => {
  if (!TRANSLATIONS[code]) TRANSLATIONS[code] = {};
});


// ── Admin Dashboard translations ─────────────────────────────────────
const ADMIN_TRANSLATIONS = {
  en: {
    adminOverview:'Overview', adminClinical:'Clinical Analytics', adminMaternal:'Maternal Health',
    adminAsha:'ASHA Performance', adminNetwork:'Network Analytics', adminEmergency:'Emergency Alerts',
    adminMessages:'Messages', adminSync:'Sync Monitor', adminAudit:'Audit Logs',
    adminRefresh:'🔃 Refresh', adminLoadDemo:'🌱 Load Demo Data',
    adminNoData:'No Data Yet',
    adminNoDataSub:'Click Load Demo Data to populate with sample rural health data.',
    adminLoadDemoBtn:'🌱 Load Demo Data',
  },
  hi: {
    adminOverview:'अवलोकन', adminClinical:'नैदानिक विश्लेषण', adminMaternal:'मातृ स्वास्थ्य',
    adminAsha:'आशा प्रदर्शन', adminNetwork:'नेटवर्क विश्लेषण', adminEmergency:'आपातकालीन अलर्ट',
    adminMessages:'संदेश', adminSync:'सिंक मॉनिटर', adminAudit:'ऑडिट लॉग',
    adminRefresh:'🔃 ताज़ा करें', adminLoadDemo:'🌱 डेमो डेटा लोड करें',
    adminNoData:'अभी कोई डेटा नहीं',
    adminNoDataSub:'सैंपल डेटा के लिए डेमो डेटा लोड करें बटन दबाएं।',
    adminLoadDemoBtn:'🌱 डेमो डेटा लोड करें',
  },
  ta: {
    adminOverview:'கண்ணோட்டம்', adminClinical:'மருத்துவ பகுப்பாய்வு', adminMaternal:'தாய்மை சுகாதாரம்',
    adminAsha:'ஆஷா செயல்திறன்', adminNetwork:'நெட்வொர்க் பகுப்பாய்வு', adminEmergency:'அவசர எச்சரிக்கைகள்',
    adminMessages:'செய்திகள்', adminSync:'ஒத்திசைவு கண்காணிப்பு', adminAudit:'தணிக்கை பதிவுகள்',
    adminRefresh:'🔃 புதுப்பி', adminLoadDemo:'🌱 டெமோ தரவு ஏற்றவும்',
    adminNoData:'இன்னும் தரவு இல்லை',
    adminNoDataSub:'டெமோ தரவு ஏற்ற கிளிக் செய்யவும்.',
    adminLoadDemoBtn:'🌱 டெமோ தரவு ஏற்றவும்',
  },
  kn: {
    adminOverview:'ಅವಲೋಕನ', adminClinical:'ಕ್ಲಿನಿಕಲ್ ವಿಶ್ಲೇಷಣೆ', adminMaternal:'ತಾಯಿ ಆರೋಗ್ಯ',
    adminAsha:'ಆಶಾ ಕಾರ್ಯಕ್ಷಮತೆ', adminNetwork:'ನೆಟ್‌ವರ್ಕ್ ವಿಶ್ಲೇಷಣೆ', adminEmergency:'ತುರ್ತು ಎಚ್ಚರಿಕೆಗಳು',
    adminMessages:'ಸಂದೇಶಗಳು', adminSync:'ಸಿಂಕ್ ಮಾನಿಟರ್', adminAudit:'ಆಡಿಟ್ ಲಾಗ್‌ಗಳು',
    adminRefresh:'🔃 ರಿಫ್ರೆಶ್', adminLoadDemo:'🌱 ಡೆಮೋ ಡೇಟಾ ಲೋಡ್ ಮಾಡಿ',
    adminNoData:'ಇನ್ನೂ ಡೇಟಾ ಇಲ್ಲ',
    adminNoDataSub:'ಡೆಮೋ ಡೇಟಾ ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ.',
    adminLoadDemoBtn:'🌱 ಡೆಮೋ ಡೇಟಾ ಲೋಡ್ ಮಾಡಿ',
  },
};
Object.keys(ADMIN_TRANSLATIONS).forEach(lang => {
  if (!TRANSLATIONS[lang]) TRANSLATIONS[lang] = {};
  Object.assign(TRANSLATIONS[lang], ADMIN_TRANSLATIONS[lang]);
});

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('gramhealth_lang') || 'en');

  const changeLang = useCallback((code) => {
    setLang(code);
    localStorage.setItem('gramhealth_lang', code);
  }, []);

  const t = useCallback((key) => {
    return TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS.en[key] ?? key;
  }, [lang]);

  const speak = useCallback((text, options = {}) => {
    if (!window.speechSynthesis) return;
    window.speechSynthesis.cancel();
    const utter = new SpeechSynthesisUtterance(text);
    utter.lang  = options.lang ?? LANG_VOICE[lang] ?? 'en-IN';
    utter.rate  = options.rate  ?? 0.88;
    utter.pitch = options.pitch ?? 1;

    // Wait for voices to load, then pick best match
    const setVoice = () => {
      const voices   = window.speechSynthesis.getVoices();
      const langCode = utter.lang.split('-')[0];
      const match    =
        voices.find(v => v.lang === utter.lang) ||
        voices.find(v => v.lang.startsWith(langCode)) ||
        voices.find(v => v.lang.startsWith('en')) ||
        voices[0];
      if (match) utter.voice = match;
      window.speechSynthesis.speak(utter);
    };

    if (window.speechSynthesis.getVoices().length > 0) setVoice();
    else { window.speechSynthesis.onvoiceschanged = setVoice; }
  }, [lang]);

  const speakPrescription = useCallback((medicine) => {
    const tx = TRANSLATIONS[lang] ?? TRANSLATIONS.en;
    const txt = `${tx.speakMed ?? 'Medicine'}: ${medicine.name}. ${tx.speakTake ?? 'Take'} ${medicine.dosage}, ${medicine.frequency}. ${tx.speakTiming ?? 'Timing'}: ${medicine.timing?.join(', ')}. ${tx.speakFor ?? 'For'} ${medicine.duration}.`;
    speak(txt);
  }, [lang, speak]);

  const speakAllMedicines = useCallback((medicines) => {
    const tx   = TRANSLATIONS[lang] ?? TRANSLATIONS.en;
    const intro = tx.speakIntro ?? 'Your prescription includes the following medicines.';
    const body  = medicines.map((m, i) =>
      `${tx.speakMed ?? 'Medicine'} ${i+1}: ${m.name}. ${tx.speakTake ?? 'Take'} ${m.dosage}, ${m.frequency}. ${tx.speakTiming ?? 'Timing'}: ${m.timing?.join(', ')}. ${tx.speakFor ?? 'For'} ${m.duration}.`
    ).join(` ${tx.speakNext ?? 'Next'}. `);
    speak(intro + ' ' + body);
  }, [lang, speak]);

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t, speak, speakPrescription, speakAllMedicines, isRTL: isRTL(lang) }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used inside LanguageProvider');
  return ctx;
};
